#!/bin/bash

KEYGEN=/usr/bin/ssh-keygen
RSA1_KEY=/opt/sshd/ssh_host_key
RSA_KEY=/opt/sshd/ssh_host_rsa_key
DSA_KEY=/opt/sshd/ssh_host_dsa_key
ECDSA_KEY=/opt/sshd/ssh_host_ecdsa_key
ED25519_KEY=/opt/sshd/ssh_host_ed25519_key

if test ! -f $RSA1_KEY; then
  $KEYGEN -q -t rsa1 -f $RSA1_KEY -C '' -N '' >&/dev/null
fi

if test ! -f $RSA_KEY; then
  $KEYGEN -q -t rsa -f $RSA_KEY -C '' -N '' >&/dev/null
fi

if test ! -f $DSA_KEY; then
  $KEYGEN -q -t dsa -f $DSA_KEY -C '' -N '' >&/dev/null
fi

if test ! -f $ECDSA_KEY; then
  $KEYGEN -q -t ecdsa -f $ECDSA_KEY -C '' -N '' >&/dev/null
fi

if test ! -f $ED25519_KEY; then
  $KEYGEN -q -t ed25519 -f $ED25519_KEY -C '' -N '' >&/dev/null
fi
